In [68]:
#(1)GET LIBRARIES
#Import libraries
import pandas as pd
import numpy as np
# import warnings filter
from warnings import simplefilter
# ignore all future warnings
simplefilter(action='ignore', category=FutureWarning)

In [69]:
#Load data files
train=pd.read_csv("C:/Users/muska/Desktop/Internship/LoanApprovalProject_101/Data/train_u6lujuX_CVtuZ9i.csv")

In [70]:
#List of column names
list(train)

['Loan_ID',
 'Gender',
 'Married',
 'Dependents',
 'Education',
 'Self_Employed',
 'ApplicantIncome',
 'CoapplicantIncome',
 'LoanAmount',
 'Loan_Amount_Term',
 'Credit_History',
 'Property_Area',
 'Loan_Status']

In [71]:
#Sample of data
train.head(10)

Loan_ID Gender Married Dependents     Education Self_Employed  \
0  LP001002   Male      No          0      Graduate            No   
1  LP001003   Male     Yes          1      Graduate            No   
2  LP001005   Male     Yes          0      Graduate           Yes   
3  LP001006   Male     Yes          0  Not Graduate            No   
4  LP001008   Male      No          0      Graduate            No   
5  LP001011   Male     Yes          2      Graduate           Yes   
6  LP001013   Male     Yes          0  Not Graduate            No   
7  LP001014   Male     Yes         3+      Graduate            No   
8  LP001018   Male     Yes          2      Graduate            No   
9  LP001020   Male     Yes          1      Graduate            No   

   ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             5849                0.0         NaN             360.0   
1             4583             1508.0       128.0             360.0   
2             3000                0.0        66.0             360.0   
3             2583             2358.0       120.0             360.0   
4             6000                0.0       141.0             360.0   
5             5417             4196.0       267.0             360.0   
6             2333             1516.0        95.0             360.0   
7             3036             2504.0       158.0             360.0   
8             4006             1526.0       168.0             360.0   
9            12841            10968.0       349.0             360.0   

   Credit_History Property_Area Loan_Status  
0             1.0         Urban           Y  
1             1.0         Rural           N  
2             1.0         Urban           Y  
3             1.0         Urban           Y  
4             1.0         Urban           Y  
5             1.0         Urban           Y  
6             1.0         Urban           Y  
7             0.0     Semiurban           N  
8             1.0         Urban           Y  
9             1.0     Semiurban           N

In [72]:
#Types of data columns
train.dtypes

Loan_ID               object
Gender                object
Married               object
Dependents            object
Education             object
Self_Employed         object
ApplicantIncome        int64
CoapplicantIncome    float64
LoanAmount           float64
Loan_Amount_Term     float64
Credit_History       float64
Property_Area         object
Loan_Status           object
dtype: object

In [73]:
#Summary statistics
train.describe()

ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
count       614.000000         614.000000  592.000000         600.00000   
mean       5403.459283        1621.245798  146.412162         342.00000   
std        6109.041673        2926.248369   85.587325          65.12041   
min         150.000000           0.000000    9.000000          12.00000   
25%        2877.500000           0.000000  100.000000         360.00000   
50%        3812.500000        1188.500000  128.000000         360.00000   
75%        5795.000000        2297.250000  168.000000         360.00000   
max       81000.000000       41667.000000  700.000000         480.00000   

       Credit_History  
count      564.000000  
mean         0.842199  
std          0.364878  
min          0.000000  
25%          1.000000  
50%          1.000000  
75%          1.000000  
max          1.000000

In [74]:
#(2)DATA CLEANING AND PREPROCESSING
#Find missing values
train.isnull().sum()

Loan_ID               0
Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

In [75]:
#Impute missing values with mean (numerical variables)
train.fillna(train.mean(),inplace=True) 
train.isnull().sum() 

Loan_ID               0
Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount            0
Loan_Amount_Term      0
Credit_History        0
Property_Area         0
Loan_Status           0
dtype: int64

In [76]:
#Impute missing values with mode (categorical variables)
train.Gender.fillna(train.Gender.mode()[0],inplace=True)
train.Married.fillna(train.Married.mode()[0],inplace=True)
train.Dependents.fillna(train.Dependents.mode()[0],inplace=True) 
train.Self_Employed.fillna(train.Self_Employed.mode()[0],inplace=True)  
train.isnull().sum() 

Loan_ID              0
Gender               0
Married              0
Dependents           0
Education            0
Self_Employed        0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
Property_Area        0
Loan_Status          0
dtype: int64

In [77]:
#Treatment of outliers
train.Loan_Amount_Term=np.log(train.Loan_Amount_Term)
print(train.Loan_Amount_Term)

0      5.886104
1      5.886104
2      5.886104
3      5.886104
4      5.886104
         ...   
609    5.886104
610    5.192957
611    5.886104
612    5.886104
613    5.886104
Name: Loan_Amount_Term, Length: 614, dtype: float64


In [78]:
#(3)PREDICTIVE MODELLING

In [79]:
#Create target variable
X=train.drop('Loan_Status',1)
y=train.Loan_Status
list(train)

['Loan_ID',
 'Gender',
 'Married',
 'Dependents',
 'Education',
 'Self_Employed',
 'ApplicantIncome',
 'CoapplicantIncome',
 'LoanAmount',
 'Loan_Amount_Term',
 'Credit_History',
 'Property_Area',
 'Loan_Status']

In [80]:
#Split train data for cross validation
from sklearn.model_selection import train_test_split
#Percentage of Training data used for modeling (train data will be applied agianst this resulting model)
#The accuracy/prediction of each run will be different because of the above
x_train,x_cv,y_train,y_cv = train_test_split(X,y,test_size=0.2)

In [81]:
#Build dummy variables for categorical variables
x_train=x_train.drop('Loan_ID',axis=1)
x_train=pd.get_dummies(x_train)
list(x_train)

['ApplicantIncome',
 'CoapplicantIncome',
 'LoanAmount',
 'Loan_Amount_Term',
 'Credit_History',
 'Gender_Female',
 'Gender_Male',
 'Married_No',
 'Married_Yes',
 'Dependents_0',
 'Dependents_1',
 'Dependents_2',
 'Dependents_3+',
 'Education_Graduate',
 'Education_Not Graduate',
 'Self_Employed_No',
 'Self_Employed_Yes',
 'Property_Area_Rural',
 'Property_Area_Semiurban',
 'Property_Area_Urban']

In [82]:
tmp = x_cv['Loan_ID']
x_cv=x_cv.drop('Loan_ID',axis=1)
x_cv=pd.get_dummies(x_cv)

In [83]:
#(a)LOGISTIC REGRESSION ALGORITHM
#Fit model
from sklearn.linear_model import LogisticRegression
model=LogisticRegression()
model.fit(x_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [84]:
#Predict values for cv data
pred_cv=model.predict(x_cv)
#Write test results in csv file
predictions=pd.DataFrame({'Loan_ID':tmp,'predictions':pred_cv}).reset_index(drop=True).to_csv('LogisticRegression_Predictions.csv')

In [85]:
#Evaluate accuracy of model
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
accuracy_score(y_cv,pred_cv) 
matrix=confusion_matrix(y_cv,pred_cv)
print(matrix)
print('LR accuracy is:')
print(round(accuracy_score(y_cv,pred_cv)*100, 2),'%')

[[ 0 31]
 [ 1 91]]
LR accuracy is:
73.98 %


In [86]:
#(b)DECISION TREE ALGORITHM
#Fit model
from sklearn import tree
dt=tree.DecisionTreeClassifier(criterion='gini')
dt.fit(x_train,y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [87]:
#Predict values for cv data
pred_cv1=dt.predict(x_cv)
#Write test results in csv file
prediction_dt=pd.DataFrame({'Loan_ID':tmp,'predictions':pred_cv1}).reset_index(drop=True).to_csv('DecisionTreeClassifier_Predictions.csv')

In [88]:
#Evaluate accuracy of model
accuracy_score(y_cv,pred_cv1) #71.54%
matrix1=confusion_matrix(y_cv,pred_cv1)
print(matrix1)
print('DT accuracy is:')
print(round(accuracy_score(y_cv,pred_cv1)*100, 2),'%')

[[20 11]
 [22 70]]
DT accuracy is:
73.17 %


In [89]:
#(c)RANDOM FOREST ALGORITHM
#Fit model
from sklearn.ensemble import RandomForestClassifier
rf=RandomForestClassifier()
rf.fit(x_train,y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [90]:
#Predict values for cv data
pred_cv2=rf.predict(x_cv)
#Write test results in csv file
prediction_rf=pd.DataFrame({'Loan_ID':tmp,'predictions':pred_cv2}).reset_index(drop=True).to_csv('RandomForestClassifier_Predictions.csv')

In [91]:
#Evaluate accuracy of model
accuracy_score(y_cv,pred_cv2) #77.23%
matrix2=confusion_matrix(y_cv,pred_cv2)
print(matrix2)
print('Rand Forest accuracy is:')
print(round(accuracy_score(y_cv,pred_cv2)*100, 2),'%')

[[18 13]
 [11 81]]
Rand Forest accuracy is:
80.49 %


In [92]:
#(d)SUPPORT VECTOR MACHINE (SVM) ALGORITHM
from sklearn import svm
svm_model=svm.SVC()
svm_model.fit(x_train,y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [93]:
#Predict values for cv data
pred_cv3=svm_model.predict(x_cv)
#Write test results in csv file
prediction_svm=pd.DataFrame({'Loan_ID':tmp,'predictions':pred_cv3}).reset_index(drop=True).to_csv('SVM_Predictions.csv')

In [94]:
#Evaluate accuracy of model
accuracy_score(y_cv,pred_cv3) #64.23%
matrix3=confusion_matrix(y_cv,pred_cv3)
print(matrix3)
print('SVM accuracy is:')
print(round(accuracy_score(y_cv,pred_cv3)*100, 2),'%')

[[ 0 31]
 [ 1 91]]
SVM accuracy is:
73.98 %


In [95]:
#(e)NAIVE BAYES ALGORITHM
from sklearn.naive_bayes import GaussianNB 
nb=GaussianNB()
nb.fit(x_train,y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [96]:
#Predict values for cv data
pred_cv4=nb.predict(x_cv)
#Write test results in csv file
prediction_nb=pd.DataFrame({'Loan_ID':tmp,'predictions':pred_cv4}).reset_index(drop=True).to_csv('GaussianNB.csv')

In [97]:
#Evaluate accuracy of model
accuracy_score(y_cv,pred_cv4) #80.49%
matrix4=confusion_matrix(y_cv,pred_cv4)
print(matrix4)
print('NBA accuracy is:')
print(round(accuracy_score(y_cv,pred_cv4)*100, 2),'%')

[[17 14]
 [ 6 86]]
NBA accuracy is:
83.74 %


In [98]:
#(f)K-NEAREST NEIGHBOR(kNN) ALGORITHM
from sklearn.neighbors import KNeighborsClassifier
kNN=KNeighborsClassifier()
kNN.fit(x_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [99]:
#Predict values for cv data
pred_cv5=kNN.predict(x_cv)
#Write test results in csv file
prediction_kNN=pd.DataFrame({'Loan_ID':tmp,'predictions':pred_cv5}).reset_index(drop=True).to_csv('KNeighborsClassifier.csv')

In [100]:
#Evaluate accuracy of model
accuracy_score(y_cv,pred_cv5) #64.23%
matrix5=confusion_matrix(y_cv,pred_cv5)
print(matrix5)
print('KNN accuracy is:')
print(round(accuracy_score(y_cv,pred_cv5)*100, 2),'%')

[[ 6 25]
 [15 77]]
KNN accuracy is:
67.48 %


In [101]:
#(g) GRADIENT BOOSTING MACHINE ALGORITHM
from sklearn.ensemble import GradientBoostingClassifier
gbm=GradientBoostingClassifier()
gbm.fit(x_train,y_train)

GradientBoostingClassifier(ccp_alpha=0.0, criterion='friedman_mse', init=None,
                           learning_rate=0.1, loss='deviance', max_depth=3,
                           max_features=None, max_leaf_nodes=None,
                           min_impurity_decrease=0.0, min_impurity_split=None,
                           min_samples_leaf=1, min_samples_split=2,
                           min_weight_fraction_leaf=0.0, n_estimators=100,
                           n_iter_no_change=None, presort='deprecated',
                           random_state=None, subsample=1.0, tol=0.0001,
                           validation_fraction=0.1, verbose=0,
                           warm_start=False)

In [102]:
#Predict values for cv data
pred_cv6=gbm.predict(x_cv)
#Write test results in csv file
prediction_gbm=pd.DataFrame({'Loan_ID':tmp,'predictions':pred_cv6}).reset_index(drop=True).to_csv('GradientBoostingClassifier.csv')

In [103]:
#Evaluate accuracy of model
accuracy_score(y_cv,pred_cv6) #78.86%
matrix6=confusion_matrix(y_cv,pred_cv6)
print(matrix6)
print('Gradient Boosting accuracy is:')
print(round(accuracy_score(y_cv,pred_cv6)*100, 2),'%')

[[17 14]
 [ 7 85]]
Gradient Boosting accuracy is:
82.93 %


In [104]:
#Select best model in order of accuracy
#Naive Bayes - 80.49%
#Logistic Regression - 78.86%
#Gradient Boosting Machine -78.86%
#Random Forest - 77.23%
#Decision Tree - 71.54%
#Support Vector Machine - 64.23%
#k-Nearest Neighbors(kNN) - 64.23%

In [105]:
#Predict values using test data (KNN)
pred_test=kNN.predict(x_cv)

In [106]:
#Write test results in csv file
predictions=pd.DataFrame(pred_test, columns=['predictions']).to_csv('Credit_Predictions.csv')

In [107]:
predictions=pd.DataFrame({'Loan_ID':tmp,'predictions':pred_test}).reset_index(drop=True)
print(predictions)

      Loan_ID predictions
0    LP001835           Y
1    LP001570           Y
2    LP002788           Y
3    LP002530           Y
4    LP001008           N
..        ...         ...
118  LP002288           Y
119  LP002142           Y
120  LP002065           Y
121  LP002130           Y
122  LP001041           Y

[123 rows x 2 columns]
